/* Generated from Algol-24.  Do not edit. */
#include "TokenType.h"

Value e_tokentype;
Value e_tokentype_tokenVleftVparen;
Value e_tokentype_tokenVrightVparen;
Value e_tokentype_tokenVleftVbracket;
Value e_tokentype_tokenVrightVbracket;
Value e_tokentype_tokenVcomma;
Value e_tokentype_tokenVdot;
Value e_tokentype_tokenVdotVdot;
Value e_tokentype_tokenVdiv;
Value e_tokentype_tokenVmod;
Value e_tokentype_tokenVminus;
Value e_tokentype_tokenVplus;
Value e_tokentype_tokenVcolon;
Value e_tokentype_tokenVsemicolon;
Value e_tokentype_tokenVslash;
Value e_tokentype_tokenVstar;
Value e_tokentype_tokenVnotVequal;
Value e_tokentype_tokenVequal;
Value e_tokentype_tokenVassign;
Value e_tokentype_tokenVgreater;
Value e_tokentype_tokenVgreaterVequal;
Value e_tokentype_tokenVless;
Value e_tokentype_tokenVlessVequal;
Value e_tokentype_tokenVidentifier;
Value e_tokentype_tokenVstring;
Value e_tokentype_tokenVchar;
Value e_tokentype_tokenVnumber;
Value e_tokentype_tokenVinteger;
Value e_tokentype_tokenVand;
Value e_tokentype_tokenVas;
Value e_tokentype_tokenVbreak;
Value e_tokentype_tokenVcase;
Value e_tokentype_tokenVclass;
Value e_tokentype_tokenVconst;
Value e_tokentype_tokenVcontinue;
Value e_tokentype_tokenVdo;
Value e_tokentype_tokenVelse;
Value e_tokentype_tokenVexit;
Value e_tokentype_tokenVgoto;
Value e_tokentype_tokenVproperty;
Value e_tokentype_tokenVoperator;
Value e_tokentype_tokenVexternal;
Value e_tokentype_tokenVfalse;
Value e_tokentype_tokenVobject;
Value e_tokentype_tokenVof;
Value e_tokentype_tokenVfor;
Value e_tokentype_tokenVif;
Value e_tokentype_tokenVin;
Value e_tokentype_tokenVis;
Value e_tokentype_tokenVnil;
Value e_tokentype_tokenVnot;
Value e_tokentype_tokenVor;
Value e_tokentype_tokenVsuper;
Value e_tokentype_tokenVthen;
Value e_tokentype_tokenVthis;
Value e_tokentype_tokenVtrue;
Value e_tokentype_tokenVtype;
Value e_tokentype_tokenVtry;
Value e_tokentype_tokenVexcept;
Value e_tokentype_tokenVraise;
Value e_tokentype_tokenVuses;
Value e_tokentype_tokenVprivate;
Value e_tokentype_tokenVpublic;
Value e_tokentype_tokenVvar;
Value e_tokentype_tokenVwhile;
Value e_tokentype_tokenVconstructor;
Value e_tokentype_tokenVfunction;
Value e_tokentype_tokenVprocedure;
Value e_tokentype_tokenVbegin;
Value e_tokentype_tokenVend;
Value e_tokentype_eof;

void init_TokenType(void) {
    e_tokentype = alg_enum_type("TokenType");
    e_tokentype_tokenVleftVparen = alg_enum_member(e_tokentype, "TOKEN_LEFT_PAREN");
    e_tokentype_tokenVrightVparen = alg_enum_member(e_tokentype, "TOKEN_RIGHT_PAREN");
    e_tokentype_tokenVleftVbracket = alg_enum_member(e_tokentype, "TOKEN_LEFT_BRACKET");
    e_tokentype_tokenVrightVbracket = alg_enum_member(e_tokentype, "TOKEN_RIGHT_BRACKET");
    e_tokentype_tokenVcomma = alg_enum_member(e_tokentype, "TOKEN_COMMA");
    e_tokentype_tokenVdot = alg_enum_member(e_tokentype, "TOKEN_DOT");
    e_tokentype_tokenVdotVdot = alg_enum_member(e_tokentype, "TOKEN_DOT_DOT");
    e_tokentype_tokenVdiv = alg_enum_member(e_tokentype, "TOKEN_DIV");
    e_tokentype_tokenVmod = alg_enum_member(e_tokentype, "TOKEN_MOD");
    e_tokentype_tokenVminus = alg_enum_member(e_tokentype, "TOKEN_MINUS");
    e_tokentype_tokenVplus = alg_enum_member(e_tokentype, "TOKEN_PLUS");
    e_tokentype_tokenVcolon = alg_enum_member(e_tokentype, "TOKEN_COLON");
    e_tokentype_tokenVsemicolon = alg_enum_member(e_tokentype, "TOKEN_SEMICOLON");
    e_tokentype_tokenVslash = alg_enum_member(e_tokentype, "TOKEN_SLASH");
    e_tokentype_tokenVstar = alg_enum_member(e_tokentype, "TOKEN_STAR");
    e_tokentype_tokenVnotVequal = alg_enum_member(e_tokentype, "TOKEN_NOT_EQUAL");
    e_tokentype_tokenVequal = alg_enum_member(e_tokentype, "TOKEN_EQUAL");
    e_tokentype_tokenVassign = alg_enum_member(e_tokentype, "TOKEN_ASSIGN");
    e_tokentype_tokenVgreater = alg_enum_member(e_tokentype, "TOKEN_GREATER");
    e_tokentype_tokenVgreaterVequal = alg_enum_member(e_tokentype, "TOKEN_GREATER_EQUAL");
    e_tokentype_tokenVless = alg_enum_member(e_tokentype, "TOKEN_LESS");
    e_tokentype_tokenVlessVequal = alg_enum_member(e_tokentype, "TOKEN_LESS_EQUAL");
    e_tokentype_tokenVidentifier = alg_enum_member(e_tokentype, "TOKEN_IDENTIFIER");
    e_tokentype_tokenVstring = alg_enum_member(e_tokentype, "TOKEN_STRING");
    e_tokentype_tokenVchar = alg_enum_member(e_tokentype, "TOKEN_CHAR");
    e_tokentype_tokenVnumber = alg_enum_member(e_tokentype, "TOKEN_NUMBER");
    e_tokentype_tokenVinteger = alg_enum_member(e_tokentype, "TOKEN_INTEGER");
    e_tokentype_tokenVand = alg_enum_member(e_tokentype, "TOKEN_AND");
    e_tokentype_tokenVas = alg_enum_member(e_tokentype, "TOKEN_AS");
    e_tokentype_tokenVbreak = alg_enum_member(e_tokentype, "TOKEN_BREAK");
    e_tokentype_tokenVcase = alg_enum_member(e_tokentype, "TOKEN_CASE");
    e_tokentype_tokenVclass = alg_enum_member(e_tokentype, "TOKEN_CLASS");
    e_tokentype_tokenVconst = alg_enum_member(e_tokentype, "TOKEN_CONST");
    e_tokentype_tokenVcontinue = alg_enum_member(e_tokentype, "TOKEN_CONTINUE");
    e_tokentype_tokenVdo = alg_enum_member(e_tokentype, "TOKEN_DO");
    e_tokentype_tokenVelse = alg_enum_member(e_tokentype, "TOKEN_ELSE");
    e_tokentype_tokenVexit = alg_enum_member(e_tokentype, "TOKEN_EXIT");
    e_tokentype_tokenVgoto = alg_enum_member(e_tokentype, "TOKEN_GOTO");
    e_tokentype_tokenVproperty = alg_enum_member(e_tokentype, "TOKEN_PROPERTY");
    e_tokentype_tokenVoperator = alg_enum_member(e_tokentype, "TOKEN_OPERATOR");
    e_tokentype_tokenVexternal = alg_enum_member(e_tokentype, "TOKEN_EXTERNAL");
    e_tokentype_tokenVfalse = alg_enum_member(e_tokentype, "TOKEN_FALSE");
    e_tokentype_tokenVobject = alg_enum_member(e_tokentype, "TOKEN_OBJECT");
    e_tokentype_tokenVof = alg_enum_member(e_tokentype, "TOKEN_OF");
    e_tokentype_tokenVfor = alg_enum_member(e_tokentype, "TOKEN_FOR");
    e_tokentype_tokenVif = alg_enum_member(e_tokentype, "TOKEN_IF");
    e_tokentype_tokenVin = alg_enum_member(e_tokentype, "TOKEN_IN");
    e_tokentype_tokenVis = alg_enum_member(e_tokentype, "TOKEN_IS");
    e_tokentype_tokenVnil = alg_enum_member(e_tokentype, "TOKEN_NIL");
    e_tokentype_tokenVnot = alg_enum_member(e_tokentype, "TOKEN_NOT");
    e_tokentype_tokenVor = alg_enum_member(e_tokentype, "TOKEN_OR");
    e_tokentype_tokenVsuper = alg_enum_member(e_tokentype, "TOKEN_SUPER");
    e_tokentype_tokenVthen = alg_enum_member(e_tokentype, "TOKEN_THEN");
    e_tokentype_tokenVthis = alg_enum_member(e_tokentype, "TOKEN_THIS");
    e_tokentype_tokenVtrue = alg_enum_member(e_tokentype, "TOKEN_TRUE");
    e_tokentype_tokenVtype = alg_enum_member(e_tokentype, "TOKEN_TYPE");
    e_tokentype_tokenVtry = alg_enum_member(e_tokentype, "TOKEN_TRY");
    e_tokentype_tokenVexcept = alg_enum_member(e_tokentype, "TOKEN_EXCEPT");
    e_tokentype_tokenVraise = alg_enum_member(e_tokentype, "TOKEN_RAISE");
    e_tokentype_tokenVuses = alg_enum_member(e_tokentype, "TOKEN_USES");
    e_tokentype_tokenVprivate = alg_enum_member(e_tokentype, "TOKEN_PRIVATE");
    e_tokentype_tokenVpublic = alg_enum_member(e_tokentype, "TOKEN_PUBLIC");
    e_tokentype_tokenVvar = alg_enum_member(e_tokentype, "TOKEN_VAR");
    e_tokentype_tokenVwhile = alg_enum_member(e_tokentype, "TOKEN_WHILE");
    e_tokentype_tokenVconstructor = alg_enum_member(e_tokentype, "TOKEN_CONSTRUCTOR");
    e_tokentype_tokenVfunction = alg_enum_member(e_tokentype, "TOKEN_FUNCTION");
    e_tokentype_tokenVprocedure = alg_enum_member(e_tokentype, "TOKEN_PROCEDURE");
    e_tokentype_tokenVbegin = alg_enum_member(e_tokentype, "TOKEN_BEGIN");
    e_tokentype_tokenVend = alg_enum_member(e_tokentype, "TOKEN_END");
    e_tokentype_eof = alg_enum_member(e_tokentype, "EOF");
}
