/* Generated from Algol-24.  Do not edit. */
#include "TokenType.h"

Value e_TokenType;
Value e_TokenType_TOKEN_LEFT_PAREN;
Value e_TokenType_TOKEN_RIGHT_PAREN;
Value e_TokenType_TOKEN_LEFT_BRACKET;
Value e_TokenType_TOKEN_RIGHT_BRACKET;
Value e_TokenType_TOKEN_COMMA;
Value e_TokenType_TOKEN_DOT;
Value e_TokenType_TOKEN_MINUS;
Value e_TokenType_TOKEN_PLUS;
Value e_TokenType_TOKEN_COLON;
Value e_TokenType_TOKEN_SEMICOLON;
Value e_TokenType_TOKEN_SLASH;
Value e_TokenType_TOKEN_STAR;
Value e_TokenType_TOKEN_NOT_EQUAL;
Value e_TokenType_TOKEN_EQUAL;
Value e_TokenType_TOKEN_ASSIGN;
Value e_TokenType_TOKEN_GREATER;
Value e_TokenType_TOKEN_GREATER_EQUAL;
Value e_TokenType_TOKEN_LESS;
Value e_TokenType_TOKEN_LESS_EQUAL;
Value e_TokenType_TOKEN_IDENTIFIER;
Value e_TokenType_TOKEN_STRING;
Value e_TokenType_TOKEN_CHAR;
Value e_TokenType_TOKEN_NUMBER;
Value e_TokenType_TOKEN_INTEGER;
Value e_TokenType_TOKEN_AND;
Value e_TokenType_TOKEN_AS;
Value e_TokenType_TOKEN_BREAK;
Value e_TokenType_TOKEN_CASE;
Value e_TokenType_TOKEN_CLASS;
Value e_TokenType_TOKEN_CONST;
Value e_TokenType_TOKEN_DO;
Value e_TokenType_TOKEN_ELSE;
Value e_TokenType_TOKEN_EXIT;
Value e_TokenType_TOKEN_FALSE;
Value e_TokenType_TOKEN_OBJECT;
Value e_TokenType_TOKEN_OF;
Value e_TokenType_TOKEN_FOR;
Value e_TokenType_TOKEN_IF;
Value e_TokenType_TOKEN_IN;
Value e_TokenType_TOKEN_IS;
Value e_TokenType_TOKEN_NIL;
Value e_TokenType_TOKEN_NOT;
Value e_TokenType_TOKEN_OR;
Value e_TokenType_TOKEN_SUPER;
Value e_TokenType_TOKEN_THEN;
Value e_TokenType_TOKEN_THIS;
Value e_TokenType_TOKEN_TRUE;
Value e_TokenType_TOKEN_TYPE;
Value e_TokenType_TOKEN_TRY;
Value e_TokenType_TOKEN_EXCEPT;
Value e_TokenType_TOKEN_RAISE;
Value e_TokenType_TOKEN_USES;
Value e_TokenType_TOKEN_PRIVATE;
Value e_TokenType_TOKEN_PUBLIC;
Value e_TokenType_TOKEN_VAR;
Value e_TokenType_TOKEN_WHILE;
Value e_TokenType_TOKEN_CONSTRUCTOR;
Value e_TokenType_TOKEN_FUNCTION;
Value e_TokenType_TOKEN_PROCEDURE;
Value e_TokenType_TOKEN_BEGIN;
Value e_TokenType_TOKEN_END;
Value e_TokenType_EOF;

void init_TokenType(void) {
    e_TokenType = alg_enum_type("TokenType");
    e_TokenType_TOKEN_LEFT_PAREN = alg_enum_member(e_TokenType, "TOKEN_LEFT_PAREN");
    e_TokenType_TOKEN_RIGHT_PAREN = alg_enum_member(e_TokenType, "TOKEN_RIGHT_PAREN");
    e_TokenType_TOKEN_LEFT_BRACKET = alg_enum_member(e_TokenType, "TOKEN_LEFT_BRACKET");
    e_TokenType_TOKEN_RIGHT_BRACKET = alg_enum_member(e_TokenType, "TOKEN_RIGHT_BRACKET");
    e_TokenType_TOKEN_COMMA = alg_enum_member(e_TokenType, "TOKEN_COMMA");
    e_TokenType_TOKEN_DOT = alg_enum_member(e_TokenType, "TOKEN_DOT");
    e_TokenType_TOKEN_MINUS = alg_enum_member(e_TokenType, "TOKEN_MINUS");
    e_TokenType_TOKEN_PLUS = alg_enum_member(e_TokenType, "TOKEN_PLUS");
    e_TokenType_TOKEN_COLON = alg_enum_member(e_TokenType, "TOKEN_COLON");
    e_TokenType_TOKEN_SEMICOLON = alg_enum_member(e_TokenType, "TOKEN_SEMICOLON");
    e_TokenType_TOKEN_SLASH = alg_enum_member(e_TokenType, "TOKEN_SLASH");
    e_TokenType_TOKEN_STAR = alg_enum_member(e_TokenType, "TOKEN_STAR");
    e_TokenType_TOKEN_NOT_EQUAL = alg_enum_member(e_TokenType, "TOKEN_NOT_EQUAL");
    e_TokenType_TOKEN_EQUAL = alg_enum_member(e_TokenType, "TOKEN_EQUAL");
    e_TokenType_TOKEN_ASSIGN = alg_enum_member(e_TokenType, "TOKEN_ASSIGN");
    e_TokenType_TOKEN_GREATER = alg_enum_member(e_TokenType, "TOKEN_GREATER");
    e_TokenType_TOKEN_GREATER_EQUAL = alg_enum_member(e_TokenType, "TOKEN_GREATER_EQUAL");
    e_TokenType_TOKEN_LESS = alg_enum_member(e_TokenType, "TOKEN_LESS");
    e_TokenType_TOKEN_LESS_EQUAL = alg_enum_member(e_TokenType, "TOKEN_LESS_EQUAL");
    e_TokenType_TOKEN_IDENTIFIER = alg_enum_member(e_TokenType, "TOKEN_IDENTIFIER");
    e_TokenType_TOKEN_STRING = alg_enum_member(e_TokenType, "TOKEN_STRING");
    e_TokenType_TOKEN_CHAR = alg_enum_member(e_TokenType, "TOKEN_CHAR");
    e_TokenType_TOKEN_NUMBER = alg_enum_member(e_TokenType, "TOKEN_NUMBER");
    e_TokenType_TOKEN_INTEGER = alg_enum_member(e_TokenType, "TOKEN_INTEGER");
    e_TokenType_TOKEN_AND = alg_enum_member(e_TokenType, "TOKEN_AND");
    e_TokenType_TOKEN_AS = alg_enum_member(e_TokenType, "TOKEN_AS");
    e_TokenType_TOKEN_BREAK = alg_enum_member(e_TokenType, "TOKEN_BREAK");
    e_TokenType_TOKEN_CASE = alg_enum_member(e_TokenType, "TOKEN_CASE");
    e_TokenType_TOKEN_CLASS = alg_enum_member(e_TokenType, "TOKEN_CLASS");
    e_TokenType_TOKEN_CONST = alg_enum_member(e_TokenType, "TOKEN_CONST");
    e_TokenType_TOKEN_DO = alg_enum_member(e_TokenType, "TOKEN_DO");
    e_TokenType_TOKEN_ELSE = alg_enum_member(e_TokenType, "TOKEN_ELSE");
    e_TokenType_TOKEN_EXIT = alg_enum_member(e_TokenType, "TOKEN_EXIT");
    e_TokenType_TOKEN_FALSE = alg_enum_member(e_TokenType, "TOKEN_FALSE");
    e_TokenType_TOKEN_OBJECT = alg_enum_member(e_TokenType, "TOKEN_OBJECT");
    e_TokenType_TOKEN_OF = alg_enum_member(e_TokenType, "TOKEN_OF");
    e_TokenType_TOKEN_FOR = alg_enum_member(e_TokenType, "TOKEN_FOR");
    e_TokenType_TOKEN_IF = alg_enum_member(e_TokenType, "TOKEN_IF");
    e_TokenType_TOKEN_IN = alg_enum_member(e_TokenType, "TOKEN_IN");
    e_TokenType_TOKEN_IS = alg_enum_member(e_TokenType, "TOKEN_IS");
    e_TokenType_TOKEN_NIL = alg_enum_member(e_TokenType, "TOKEN_NIL");
    e_TokenType_TOKEN_NOT = alg_enum_member(e_TokenType, "TOKEN_NOT");
    e_TokenType_TOKEN_OR = alg_enum_member(e_TokenType, "TOKEN_OR");
    e_TokenType_TOKEN_SUPER = alg_enum_member(e_TokenType, "TOKEN_SUPER");
    e_TokenType_TOKEN_THEN = alg_enum_member(e_TokenType, "TOKEN_THEN");
    e_TokenType_TOKEN_THIS = alg_enum_member(e_TokenType, "TOKEN_THIS");
    e_TokenType_TOKEN_TRUE = alg_enum_member(e_TokenType, "TOKEN_TRUE");
    e_TokenType_TOKEN_TYPE = alg_enum_member(e_TokenType, "TOKEN_TYPE");
    e_TokenType_TOKEN_TRY = alg_enum_member(e_TokenType, "TOKEN_TRY");
    e_TokenType_TOKEN_EXCEPT = alg_enum_member(e_TokenType, "TOKEN_EXCEPT");
    e_TokenType_TOKEN_RAISE = alg_enum_member(e_TokenType, "TOKEN_RAISE");
    e_TokenType_TOKEN_USES = alg_enum_member(e_TokenType, "TOKEN_USES");
    e_TokenType_TOKEN_PRIVATE = alg_enum_member(e_TokenType, "TOKEN_PRIVATE");
    e_TokenType_TOKEN_PUBLIC = alg_enum_member(e_TokenType, "TOKEN_PUBLIC");
    e_TokenType_TOKEN_VAR = alg_enum_member(e_TokenType, "TOKEN_VAR");
    e_TokenType_TOKEN_WHILE = alg_enum_member(e_TokenType, "TOKEN_WHILE");
    e_TokenType_TOKEN_CONSTRUCTOR = alg_enum_member(e_TokenType, "TOKEN_CONSTRUCTOR");
    e_TokenType_TOKEN_FUNCTION = alg_enum_member(e_TokenType, "TOKEN_FUNCTION");
    e_TokenType_TOKEN_PROCEDURE = alg_enum_member(e_TokenType, "TOKEN_PROCEDURE");
    e_TokenType_TOKEN_BEGIN = alg_enum_member(e_TokenType, "TOKEN_BEGIN");
    e_TokenType_TOKEN_END = alg_enum_member(e_TokenType, "TOKEN_END");
    e_TokenType_EOF = alg_enum_member(e_TokenType, "EOF");
}
